### ISSUE TITLE
Can't find dataset

### ISSUE THREAD

**Issue by kjwoo31** [ai4r/AIR-Act2Act#1]
ETRI 데이터 허브에서 dataset을 찾지 못하고 있습니다. 아래 list에서 찾아보고 있는데, Act2Act에 사용되는 dataset은 아직 공개되지 않은 건가요?  (<http://nanum.etri.re.kr:8080/etriPortal/share/list>)

**Comment by wrko** [comment]
Please visit the following website.
[http://nanum.etri.re.kr:8080/etriPortal/login?language=en](http://nanum.etri.re.kr:8080/etriPortal/login?language=en)
It's the web page for the foreigners written in English.

**Comment by wrko** [comment]
이슈에도 코멘트 달았지만,

영문 페이지에만 데이터가 올라가 있습니다.

 

따라서 아래 페이지를 방문해 주세요.

 <http://nanum.etri.re.kr:8080/etriPortal/login?language=en> http://nanum.etri.re.kr:8080/etriPortal/login?language=en

 

고우리 드림.

**Comment by kjwoo31** [comment]
외국인으로 회원가입하였더니 해결되었습니다. 감사합니다.

**Comment by zebehn** [comment]
아래 링크로 가면 한국어 페이지에서 사용자 등록한 사람도 접근할 수 있네요.

- AIR-Act2Act - Body index, 3D skeleton, Robotic data: http://nanum.etri.re.kr:8080/etriPortal/share/view?id=81
- AIR-Act2Act - RGB Video: http://nanum.etri.re.kr:8080/etriPortal/share/view?id=75
- AIR-Act2Act - Depth Map: http://nanum.etri.re.kr:8080/etriPortal/share/view?id=74
- AIR-Act2Act - Introduction: http://nanum.etri.re.kr:8080/etriPortal/share/view?id=73
