### ISSUE TITLE
Modules used in viewer.py

### ISSUE THREAD

**Issue by kjwoo31** [ai4r/AIR-Act2Act#2]
Anaconda에서 env(python=3.6)를 만들어 test한 결과, 아래와 같은 모듈이 추가로 필요했습니다. Readme의 Installation 부분에 추가하면 도움이 될 것입니다.
> pip install pillow opencv-python matplotlib simplejson

**Comment by wrko** [comment]
Thank you for your kind comments.

**Comment by kjwoo31** [comment]
Ubuntu에서는 pip install하였을 때 viewer가 정상적으로 실행되었는데, Windows10 위에서 다시 해보았더니 아래와 같은 에러가 발생하였습니다. Matplotlib의 경우, pip 대신 conda install을 사용하여 해결하였습니다.

from . import ft2font
ImportError: DLL load failed: 지정된 모듈을 찾을 수 없습니다.

(기존)
> pip install pillow opencv-python matplotlib simplejson

(수정)
> pip install pillow opencv-python simplejson
> conda install matplotlib

**Comment by wrko** [comment]
I have updated the README.md as you recommended.
